version: '3'
services:
  service1:
    container_name: C1
    build: 
      context: ./service1
  service2:
    container_name: C2
    build:
      context: ./service2
  nginx:
    image: "nginx:latest"
    container_name: nginx
    depends_on:
      - service1
      - service2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx2.conf:/etc/nginx/conf.d/nginx2.conf
    ports:
#      - "8099:80"
      - "8090:90"
      - "8091:91"
